### ISSUE TITLE
Use of deprecated feature in python module

### ISSUE THREAD

**Issue by jhenin** [BranniganLab/safep#38] opened 2024-03-18 14:48 UTC
On some Python installs, we could not plot the main plot of the Basic estimator notebook, due to incompatible python modules.

There were warnings about installed versions, however safep and dependencies were freshly installed using pip.
```
/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
$HOME/.local/lib/python3.10/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
$HOME/.local/lib/python3.10/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.2' currently installed).
```

The error that occurred was then:
```
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_2808/4143065175.py in <module>
----> 1 fig, axes = safep.plot_general(cumulative, None, perWindow, None, RT)
      2 fig.suptitle(changeAndError)
      3 plt.savefig(f'{path}FEP_general_figures.pdf')

~/.local/lib/python3.10/site-packages/safep/plotting.py in plot_general(cumulative, cumulativeYlim, perWindow, perWindowYlim, RT, width, height, PDFtype, fontsize)
    123     # Per-window change in kcal/mol
    124     eachAx.errorbar(perWindow.index, perWindow.BAR.df*RT, yerr=perWindow.BAR.ddf, marker=None, linewidth=1)
--> 125     eachAx.plot(perWindow.index, perWindow.EXP.dG_f*RT, marker=None, linewidth=1, alpha=0.5)
    126     eachAx.errorbar(perWindow.index, -perWindow.EXP.dG_b*RT, marker=None, linewidth=1, alpha=0.5)
    127     eachAx.set(ylabel=r'$\mathrm{\Delta} G_\lambda$'+'\n'+r'$\left(kcal/mol\right)$', ylim=perWindowYlim)

/usr/lib/python3/dist-packages/matplotlib/axes/_axes.py in plot(self, scalex, scaley, data, *args, **kwargs)
   1630         """
   1631         kwargs = cbook.normalize_kwargs(kwargs, mlines.Line2D)
-> 1632         lines = [*self._get_lines(*args, data=data, **kwargs)]
   1633         for line in lines:
   1634             self.add_line(line)

/usr/lib/python3/dist-packages/matplotlib/axes/_base.py in __call__(self, data, *args, **kwargs)
    310                 this += args[0],
    311                 args = args[1:]
--> 312             yield from self._plot_args(this, kwargs)
    313 
    314     def get_next_color(self):

/usr/lib/python3/dist-packages/matplotlib/axes/_base.py in _plot_args(self, tup, kwargs, return_kwargs)
    485 
    486         if len(xy) == 2:
--> 487             x = _check_1d(xy[0])
    488             y = _check_1d(xy[1])
    489         else:

/usr/lib/python3/dist-packages/matplotlib/cbook/__init__.py in _check_1d(x)
   1325                     message='Support for multi-dimensional indexing')
   1326 
-> 1327                 ndim = x[:, None].ndim
   1328                 # we have definitely hit a pandas index or series object
   1329                 # cast to a numpy array.

~/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py in __getitem__(self, key)
   5417         # Because we ruled out integer above, we always get an arraylike here
   5418         if result.ndim > 1:
-> 5419             disallow_ndim_indexing(result)
   5420 
   5421         # NB: Using _constructor._simple_new would break if MultiIndex

~/.local/lib/python3.10/site-packages/pandas/core/indexers/utils.py in disallow_ndim_indexing(result)
    339     """
    340     if np.ndim(result) > 1:
--> 341         raise ValueError(
    342             "Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer "
    343             "supported. Convert to a numpy array before indexing instead."

ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.
```

Is this something that can be addressed at a safep level, or is it an incompatibility between the installed matplotlib and pandas?

**Comment by EzryStIago** [comment] 2024-03-18 15:17
@jhenin This looks like something we could address on our end, but I'm unable to reproduce your error.
Can you share your `pip list` so I can compare our package versions? 
Maybe we just need to update our package requirements so we ensure everything is up-to-date.

**Comment by jhenin** [comment] 2024-03-27 17:41
According to this, https://github.com/mwaskom/seaborn/issues/3312 requiring matplotlib version 3.6.0 or greater should solve the issue.

**Comment by EzryStIago** [comment] 2024-04-22 14:27
I believe this issue is resolved with the updated dependencies.

**Closed by EzryStIago** 2024-04-22 14:27 UTC
